build:
  version: "1.0"

loans:
  message: "Welcome to EazyBank loans related production APIs "
  contactDetails:
    name: "Sabarno Biswas - Product Owner"
    email: "sabarno@eazybank.com"
  onCallSupport:
    - (453) 392-4829