build:
  version: 1.5.0
loans:
  message: "Welcome to EazyBank lans related local APIs "
  contactDetails:
    name: "Sabarno Biswas - Developer"
    email: "sabarnobiswas@gmail.com"
  onCallSupport:
    - (+91) 8420241803