build:
  version: "1.0"

loans:
  message: "Welcome to EazyBank loans related QA APIs "
  contactDetails:
    name: "Sabarno Biswas - QA Lead"
    email: "sabarno@eazybank.com"
  onCallSupport:
    - (666) 265-3765